---
  root: true
  env:
    # 是否在浏览器运行
    browser: true
    # 是否支持node环境
    node: true
    # 是否支持es6
    es6: true
  extends: 'eslint:recommended'
  parserOptions:
    sourceType: module
  # 错误等级（off/0: 关闭规则，warn/1: 开启警告，error/2: 开启错误）
  # http://eslint.org/docs/rules/
  rules:
    # --- POSSIBLE ERROR --- #
    # 禁止状态语句中赋值（default: except-parens），可以在外面添加一对括号
    ##TODO no-cond-assign
    # 禁止使用console
    no-console:
      - warn
      - allow:
        - warn
        - error
    # 禁止状态语句的判断结果恒定
    ##TODO no-constant-condition
    # 禁止正则匹配中匹配ASCII范围在 0-31的内容
    ##TODO no-control-regex
    # 禁止使用debugger
    ##TODO no-debugger
    # 禁止形参重复
    ##TODO no-dupe-args
    # 禁止对象中重复的key值
    ##TODO no-dupe-keys
    # 禁止switch-case中重复case
    ##TODO no-duplicate-case
    # 禁止正则表达式中的空类（[]）
    ##TODO no-empty-character-class
    # 禁止空块级语句（正确写法：if (condition) {// empty}/if (condition) {/* empty */}）
    no-empty:
      - error
      - allowEmptyCatch: true
    # 禁止对错误信息重新赋值
    ##TODO no-ex-assign
    # 禁止没必要的boolean转换
    ##TODO no-extra-boolean-cast
    # 禁止多余的括号
    ## no-extra-parens
    # 禁止没必要的分号
    ##TODO no-extra-semi
    # 禁止方法赋值
    ##TODO no-func-assign
    # 禁止内部申明
    ##TODO no-inner-declarations
    # 禁止无效的正则表达式
    ##TODO no-invalid-regexp
    # 禁止异常的空白符
    ##TODO no-irregular-whitespace
    # 禁止调用全局对象属性作为方法
    ##TODO no-obj-calls
    # 禁止直接使用Object.prototype内建的方法
    ## no-prototype-builtins
    # 禁止在正则表达式中出现多个连续空白
    ##TODO no-regex-spaces
    # 禁止使用稀疏数组
    ##TODO no-sparse-arrays
    # 禁止在正常字符串中出现模板占位符语法
    ## no-template-curly-in-string
    # 禁止模棱两可的多行表达式（PS: 语法结束加分号）
    ##TODO no-unexpected-multiline
    # 禁止出现在return，throw，continue，break声明之后无法访问的代码（PS: 要把return, throw, continue, break放在执行最后）
    ##TODO no-unreachable
    # 禁止在finally块中添加控制流语句
    ##TODO no-unsafe-finally
    # 禁止相关操作中不安全的否定操作
    ## no-unsafe-negation
    # 当检查NaN时，需要调用isNaN()
    ##TODO use-isnan
    # 强制有效JSDoc注释
    ## vaild-jsdoc
    # 强制与typeof比较的字符串是有效的字符串
    ##TODO valid-typeof
    # --- BEST PRACTICES --- #
    # 禁止在case/default条例中直接词法声明（PS: 必须在case/default后面添加大括号包裹）
    ##TODO no-case-declarations
    # 禁止空解构模式（PS: ES6）
    ##TODO no-empty-pattern
    # 禁止使用case语句不进行return/break/throw/fallthrough注解
    ##TODO no-fallthrough
    # 禁止使用八进制内容
    ##TODO no-octal
    # 禁止变量重声明
    ##TODO no-redeclare
    # 禁止将自己复制给自己
    ##TODO no-self-assign
    # 禁止未使用的label
    ##TODO no-unused-labels

    # 缩进格式 4个空格
    indent:
      - error
      - 4
    linebreak-style:
      - error
      - unix
    # 字符串引号 单引号
    quotes:
      - error
      - single
    # 分号 总是添加
    semi:
      - error
      - always
    # --- STRICT MODE --- #
    # 需要或者静止`strict mode`指令
    # strict
    # --- VARIABLES --- #
    # 禁止删除变量
    ##TODO no-delete-var
    # 禁止未声明变量
    # no-undef
    # 禁止声明而从未使用的变量
    no-unused-vars:
      - error
      - local
    # --- NODE.JS & COMMONJS --- #
    # --- STYLISTIC ISSUES --- #
    # 禁止在缩进时混合使用spaces和tabs
    ##TODO no-mixed-spaces-and-tabs
    # --- ECMASCRIPT 6 --- #
    # 检查构造器是否正确调用super()方法
    ##TODO constructor-super
    # 禁止修改类声明的变量
    ##TODO no-class-assign
    # 禁止修改用const声明的变量
    ##TODO no-const-assign
    # 禁止出现类成员重名
    ##TODO no-dupe-class-members
    # 禁止使用new Symbol方式（PS: 无意义）
    ##TODO no-new-symbol
    # 禁止在构造函数调用super()之前使用this/super
    ##TODO no-this-before-super
    # 禁止generator函数必须有yield
    ##TODO require-yield


